### ISSUE TITLE
Conflict with Windows 10 virtual desktops shortcut

### ISSUE THREAD

**Issue by joserebelo** [stefansundin/superf4#17]
On Windows 10, you can use Ctrl+Win+F4 to close the current virtual desktop, which current can't be used, because it triggers SuperF4's Win+F4 shortcut.

Would it be possible for the shortcut not be triggered if Ctrl is also being held?

**Comment by stefansundin** [comment]
Hi @joserebelo.

Yes, that should be possible. Thanks for the suggestion.
