### ISSUE TITLE
Super F4 can give my keyboard input lag.

### ISSUE THREAD

**Issue by ThePenitence** [stefansundin/superf4#19]
So I just discovered this was caused by Super F4 today. I have been using Super F4 for a little while now and just the other day for some reason when I started up Tera, my keyboard was given delayed inputs, as in I press a key and it gets read by the PC seconds later. The problem didn't go away after closing Tera unless I rebooted. When it happened again today I decided to look at my system tray and noticed Super F4 was un-clickable, so I closed it with task manager and the problem was instantly gone without a reboot. I have had input delays happen sparingly often but I'm not sure if I had Super F4 during all those times. But it definitely somehow caused it this time only when running Tera.

Setting notes: 
Super F4 was running on elevated and with Timer check on. 
Windows 10, 64 bit.

**Comment by stefansundin** [comment]
Hi there,

Can you try the build found here: https://github.com/stefansundin/superf4/issues/1#issuecomment-269853636

Thank you.

**Comment by BytesOfCookies** [comment]
I've had this exact issue multiple times except I was not using timer check. (p.s the UAC prompt at startup is really annoying)

**Comment by ThePenitence** [comment]
Just checking this now, I will try the build you linked, though I cannot seem to overwrite my existing exe of SuperF4 with this one. Not really important though since it's a standalone executable.

Side note: Tried playing Paragon the other day, same lag issue happened until I shut off SuperF4. Think it might occur often with high resolution gaming.

**Comment by Philip56901** [comment]
If you change your resolution or change resolution function (fullscreen to windowed or etc.) it causes your keyboard to have large amount of input lag and also have most keys not working

**Comment by rapsaGnauJ** [comment]
This happens to me as well. I thought it was caused by my new monitor, as I recently changed from a 1080p to a 2160p. It's an extrange monitor error but it was the only change I made to my computer. After some research, I discovered that this was caused by Super F4 whenever I (or any aplication on my computer) change the resolution.

It's so sad because I loved Super F4 and now I just have to stop using it until this gets fixed (and it doesn't look like that's gonna happen).

**Comment by gigglearrows** [comment]
Happened to my as well playing destiny 2. Superf4 actually caused Destiny 2 to lag and crash whenever I used the keyboard ingame. And severe keyboard lag after i quit the game until i ended the superf4 task

**Comment by OldMartin** [comment]
I have same issue but i just run the program i use league and bang input lag over 9000 lost the game for this issue

**Comment by sneaky4oe** [comment]
Never had it on windows 8. Now I have lags on win10.

**Comment by stefansundin** [comment]
I released a new version with the fix: https://github.com/stefansundin/superf4/releases/tag/v1.4
