### ISSUE TITLE
Can't close installation

### ISSUE THREAD

**Issue by kluplau** [stefansundin/superf4#21]
Somewhat ironic, that you can't close the installation dialog. I read about the installation and wanted to bail out, but I couldn't.

![image](https://user-images.githubusercontent.com/1536598/31512579-c4d82564-af8b-11e7-90fd-bc356caee8d2.png)

**Comment by stefansundin** [comment]
When you reach that step of the setup, there's nothing to bail out from, you've already installed SuperF4. That page is a post-installation step.

You have to click Next, then Finish, then run the uninstaller.
