### ISSUE TITLE
Using this causes severe keyboard lag

### ISSUE THREAD

**Issue by calebrader** [stefansundin/superf4#22]

**Comment by gigglearrows** [comment]
+1 This cause severe lags in Destiny 2 (screen froze or game crashed whenever I used keyboard). Severe keyboard lag after the game closed until I ended the superf4 task

**Comment by rapsaGnauJ** [comment]
I used superf4 with a 1920x1080 tv and it worked correctly. Replaced it with a 4k monitor and everytime windows changed resolution (changing settings or by a third party app) the keyboard gained a lot of input lag. Works correctly without superf4. Had to stop using it due to that.

**Comment by Trololocos** [comment]
This is still a problem, but only after opening StarCraft 2
Windows 10 Pro x64

**Comment by stefansundin** [comment]
I released a new version that hopefully fixes the issue. https://github.com/stefansundin/superf4/releases/tag/v1.4

There may be a separate but similar issue when changing resolutions, but I have not been able to reproduce that.
