### ISSUE TITLE
Even with v1.3 it still gives a UAC prompt on startup.

### ISSUE THREAD

**Issue by BytesOfCookies** [stefansundin/superf4#23]
Hi,
When I check the elevate on startup box it gives a UAC prompt on startup even after updating to v1.3 which specifies it fixes in the changelog.

**Comment by stefansundin** [comment]
The entry in the changelog relates to the installer, which doesn't ask for administrator privileges anymore.

If you check elevate, you will still get an UAC prompt.

**Comment by BytesOfCookies** [comment]
Ok sorry I read that wrong.
