### ISSUE TITLE
Rip pc

### ISSUE THREAD

**Issue by tygotjeeeh** [stefansundin/superf4#24]
I installed the software on my brand new laptop, 
I used the software because a program was not working, i accidently used it twice so now i think my windows or something else is not working, reboot doesnt work either
Please help asap

**Comment by SirWindfield** [comment]
Realistically, how should we be able to help you if your PC does not start at all? Try to boot into safe mode first, this should disable all programs and should not start anything that is set on `start on boot`. Try then to uninstall SuperF4. 
Though that I find it curious how the program should super close your Windows installation... I just tried it and it works on my PC still, even after pressing twice.

**Comment by stefansundin** [comment]
Thanks @SirWindfield for helping out!

And sorry everyone that I'm very inactive here. Just busy. :(

**Comment by tygotjeeeh** [comment]
Got it done with a hard boot already 
(Press the off button for 20 secs)

**Comment by SirWindfield** [comment]
Good to hear that it worked out! Just to be sure, would you mind to test if SuperF4 was actually the program that killed your windows by trying it out again? :smile: I couldn't reproduce it on my machine.

**Comment by tygotjeeeh** [comment]
Was nothing, sorry for blaming the program

**Comment by al216042** [comment]
It also happened to me. It seems SuperF4 is ending the "Windows Explorer" task, the one who's doing all the taskbar and desktop stuff. A quick solution is to sign out form the Ctrl+Alt+Del menu and relogging in.

**Comment by stefansundin** [comment]
I released a new version today that has a process blacklist with `explorer.exe` in it by default, which should hopefully resolve this issue. https://github.com/stefansundin/superf4/releases/tag/v1.4
