### ISSUE TITLE
It blacks out my screen, always

### ISSUE THREAD

**Issue by Andrack** [stefansundin/superf4#31]
I have heard wonders about this program, the issue is this: Whenever I try to use it, it always blacks out my screen and just leaves me with the mouse cursor, like if there was nothing, had to restart my computer with the power button on the case, I have to say that when that happened, I just opened a folder to try out how this really works. When I restated, everything was back to normal, so I tried to investigate what was the issue, and ended up in this video:
https://www.youtube.com/watch?v=u87mH7IWJU4
The kid in this video says, that if you dont select the window that you want to close, what happened to me is what will happen, explaining that you can completely turn off all the processes that your pc may be doing, so I then thought, well maybe I just didn´t click on the window the last time, so this next try I assured that the window was selected, so I tried again, and the same thing happened, It just blacked out completely, I don´t know if this is only meant to work with programs that don´t respond, and that´s why it happens, or if you can really just use it to close any program without mattering if is ok or if it doesn´t respond

**Comment by SirWindfield** [comment]
You probably just killed `explorer.exe`. try it again and if you black screen, press `ctrl shift esc`. This should open the task manager. Under File->New Process type `explorer.exe` and press enter.

**Comment by Andrack** [comment]
I mean the problem is not that I cannot use the computer again. As I said, I just restart the system and everything is back to normal, It just seems that whenever I want to use the program it would just do that, like if it just works to black out the screen not to close windows, games, etc.

**Comment by stefansundin** [comment]
The new version today has a process blacklist, with `explorer.exe` in it by default. Hopefully that resolves this issue. https://github.com/stefansundin/superf4/releases/tag/v1.4
