### ISSUE TITLE
SuperF4 conflicts with Nvidia GeForce Experience optimal settings for Heroes of the Storm

### ISSUE THREAD

**Issue by Dyras** [stefansundin/superf4#4]
Hi! Love the program, it's one of the hidden golden corns in this world!

However, one thing that annoys the hell out of me is this: I have a GTX 1070, and when I play Heroes of the Storm with the optimal settings the keyboard stops working all of a sudden. There is a craaaaazy delay, similar to what is described in another issue here.

Here's how to reproduce. You need an Nvidia GPU, preferably of the newer variety. Download Nvidia GeForce Experience. Not the new crap that barely works, but the old GFE 2.
Under the settings for Heroes of the Storm, pick something under Dynamic Super Resolution.
https://i1.someimage.com/9tXjYu6.png <--- That right there
Now start the game while running SuperF4 in the background and you will notice you can't do shit with the keyboard. The mouse on the other hand works fine. Exit the game and well, still no keyboard for you!

To bring your keyboard back to life you have to right click the start menu, open the task manager and kill superf4.exe. Also note that your desktop shortcuts have been re-arranged.

I hope you can fix this, because I really can't live without SuperF4 and I would hate not to use... Uh... Dynamic Super Resolution, whatever the hell that is!

Tried with, and without TimerCheck enabled.

**Comment by Dyras** [comment]
Oh, and I start SuperF4 through a shortcut in the Autostart-folder if that matters.

**Comment by stefansundin** [comment]
Hmm.. One thing I could try is compile a new binary that has a new setting that would disable the keyboard hook and that way you would be able to use the program with only TimerCheck enabled. Without a keyboard hook, I don't think there would be any way SuperF4 would be able to break in this manner.

I'll try to get it done later tonight.

Unfortunately I don't think I will be able to test your specific use case, though.

Thanks for reporting!

**Comment by stefansundin** [comment]
Okay, I have created a custom version for you to test. This version does not use a keyboard hook at all, it only uses "TimerCheck". To make it simpler for me to produce this version, it's not even possible to disable SuperF4 now, you have to exit it completely. The "xkill" or Win+F4 feature has also been removed.

Anyway, test it out and let me know how it works.

[SuperF4 v1.3 NoHook.zip](https://github.com/stefansundin/superf4/files/471362/SuperF4.v1.3.NoHook.zip)

**Comment by Dyras** [comment]
Yeah so, with the new version this happened
I pasted the new version on top of the version I had already installed, then I started SuperF4.exe and ran Heroes of the Storm. In game the keyboard works, great! But wait! The mouse isn't working (AHAHAHAH!) and so I kill the game with SuperF4. After that the SuperF4 icon at the bottom right corner is completely "dead", regardless of what mouse button I click nothing happens. In the task manager I kill SuperF4 and then I restart the .exe, and lo and behold, everything now works just fine!

**Comment by Ultrimo** [comment]
Hi, I love your program and I just made an account to say that this issue had been bugging me for the past day. I just bought a 1070 and used Nvidia Gforce experience to optimise my games on 
Windows 10 64 bit. DOTA 2 and Dark souls 3 both automatically got assigned a DSR. The keyboard lag was intense and it was totally unplayable. Closing the game did nothing. Finally I tried closing superaltf4 to try and see if that could be it and was very surprised to see that it began running perfectly. The NoHook you provided doesn't cause the keyboard lag but it doesn't work either, not even the right click menu. The only way to close it is through task manager. Sorry if I repeated what was said already but I just wanted to confirm that I'm experiencing the same. Thank you for your program.

**Comment by stefansundin** [comment]
Hi @Dyras.

I have made a new build that includes the fix by vmrob in #5. Can you try it and see if it fixes the problem?

File: [SuperF4-no-block.zip](https://github.com/stefansundin/superf4/files/679513/SuperF4-no-block.zip)

Sorry for the long delay in looking into this. All credit goes to vmrob for finding the problem.

Thank you!

**Comment by Dyras** [comment]
@stefansundin This new version works wonders, thanks! I'd suggest you make it the new standard in the next version!

**Comment by stefansundin** [comment]
Great! I definitely will. I'm going to leave this issue open until I get the chance to do so. Thanks for testing!

**Comment by pix0wl** [comment]
I can also confirm that it's working now. 
I had the issue with high resolution downsampling (DSR via Nvidia driver) in games on Windows 10. 
The Keyboard wasn't reacting at all.

@vmrob & @stefansundin 
Thank you guys for fixing it.

**Comment by stefansundin** [comment]
New version is out, so closing this.
