### ISSUE TITLE
Info on the issue with Geforce experience

### ISSUE THREAD

**Issue by XenSide** [stefansundin/superf4#6]
It is not an issue "with" Nvidia Drivers, it's an issue with one of theirs features: DSR (Dinamic Super Resolution), basicly if any program runs at a higher resolution than native this will cause SuperF4 to delay keyboard input of a good a minute or so and "kill" (as another user said) SuperF4 icon (not able to interact with it anyhow), killing it by taskmanager works.

Hope this little info helps you, I've also tried to use the "TimerCheck" feature and nothing changed

EDIT: I'm now testing the NoHook version I found on another Issue thread, now that I think of it, I should have commented there, Sorry.

EDIT2: Testing Results

Using the NoHook app the problem disappears **BUT**: the app doesn't work anymore with those games (the ones downscaled with DSR) and the icon freezes just like before, also, for the first 4-5 seconds of the **FISRT** launch of one of these games the mouse didn't respond anymore.

**Comment by stefansundin** [comment]
Hi @XenSide.

I have made a new build that includes the fix by vmrob in #5. Can you try it and see if it fixes the problem?

File: [SuperF4-no-block.zip](https://github.com/stefansundin/superf4/files/679513/SuperF4-no-block.zip)

Sorry for the long delay in looking into this. All credit goes to vmrob for finding the problem.

Thank you!

**Comment by CoolOppo** [comment]
@stefansundin you should do another release since you merged that. Sounds pretty important.

**Comment by stefansundin** [comment]
New version is out with the fix. Hopefully that resolves this.
