### ISSUE TITLE
explorer.exe

### ISSUE THREAD

**Issue by 07416** [stefansundin/superf4#8]
I started xkill and clicked a misbehaving app in my taskbar, explorer.exe was shut down. I don't think there's any benefit in killing explorer.exe.
"Universal Pause Button" developer has excluded the process: https://github.com/ryanries/UniversalPauseButton/releases/tag/v1.0.2

**Comment by marcofugaro** [comment]
Yup, it kills my explorer also when I'm trying to quit a game

**Comment by camperboy1000** [comment]
Clicking an application in the taskbar with xkill kills explorer because the taskbar is managed by explorer. You can always restart explorer by opening task manager, clicking "File", "Run new task", and then type "explorer" in the box.

**Comment by stefansundin** [comment]
The new version today has a process blacklist, with `explorer.exe` in it by default. Hopefully that resolves this issue. https://github.com/stefansundin/superf4/releases/tag/v1.4
