### ISSUE TITLE
superf4 major issue

### ISSUE THREAD

**Issue by pengunkey** [stefansundin/superf4#9]
Hello, I just installed superf4 and was testing by closing a spare folder window on my pc. Closing caused the screen to go black and removed the taskbar, the other applications I had open remained open. I had to manually shut down my pc as the windows icon was no longer there and attempting to alt-f4 on the desktop wasn't having any effect. After spending a considerable amount of time booting up again the pc appears to have reset to factory default except that all my games and programs are still on it. It removed chrome as my primary browser, my desktop images and the majority of my desktop shortcuts, any customizations I had on the taskbar, mouse and keyboard customizations, and all updates for my games and programs. I haven't been able to find any similar issue on the internet regarding this program. I'm using windows 10 64-bit, if you need any further information about my computer's specs please let me know, you can reach me through email at samurainarwhal@gmail.com; any and all help is appreciated, thank you.

**Comment by pengunkey** [comment]
Upon reinspection, none of the games or anything with hard save data remained. The pc only remembers having the game but it doesn't actually have it installed or kept any of the saves, yet the same amount of hard drive space is being taken up.

**Comment by CyanLumi** [comment]
I recently just had a problem similar to this (literally 5 mins ago). My computer setup is a tv (main monitor) and a laptop connected together. Upon first use of this application, the screens go black for a few seconds and my main monitor worked whilst second monitor went black. Upon inspection, it seemed that it changed the monitor modes from extend display to use monitor 1 only.

As to how to fix your computer the only thing I can recommend is to restore ur PC to a previous time.

**Comment by stefansundin** [comment]
Using SuperF4 on an explorer window will terminate explorer.exe, which causes the desktop to "disappear". It might be hard to get explorer running again. One way is to launch the process manager with Ctrl+Shift+Esc and launching explorer.exe from there. There have been some suggestions to stop SuperF4 from killing explorer.exe, and I might implement it in a future version.

I can't see how SuperF4 would have caused your files to disappear though. I would say that if you manually shut down the computer by disconnecting the power, this somehow put your harddrive into a bad state and then when you booted it Windows tried to recover and reset your user for some reason.

SuperF4 never deletes any file or modifies your system. The only thing it does is terminate processes. I am afraid I can't help you recover your files.

**Comment by pengunkey** [comment]
Thank you for replying so quickly, I downloaded several new programs along with this one so I made a backup in case anything went wrong (thank goodness). Thanks for explaining what happened as well, your explanation actually answered a lot of my questions about what happened.

**Comment by stefansundin** [comment]
The new version released today has a process blacklist, with `explorer.exe` on it by default.
